# This is a basic workflow to help you get started with Actions
name: Dry Run 1

# Controls when the workflow will run
# Controls what will trigger the workflow.
# Change it to your needs.
on:
    # A new push to the "main" branch. 
    push:
       branches: [ "main" ]
     # A new pull request to the "main" branch.
    pull_request:
       branches: [ "main" ]
   
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  releases:
    name: debug apk
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
        working-directory: './blackjack_flutter'
      - run: flutter build apk
        working-directory: './blackjack_flutter'
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: ./blackjack_flutter/build/app/outputs/flutter-apk/app-release.apk
#      - uses: ncipollo/release-action@v2
#        with:
#         artifacts: "build/app/outputs/flutter-apk/*.apk"
#         token: $
